version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: limpeza
      POSTGRES_USER: gabi
      POSTGRES_PASSWORD: gabi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  limpeza-gabi:
    image: limpeza-gabi
    ports:
      - "8080:80"
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
